name       : python-pillow
version    : 8.3.2
release    : 26
source     :
    - https://github.com/python-pillow/Pillow/archive/refs/tags/8.3.2.tar.gz : 8252b6b514aed2743abb5b7259b3253d6c4bf86902b9c5acd33fe79d24ec7b2f
license    : MIT
component  : programming.python
summary    : The friendly PIL fork (Python Imaging Library)
description: |
    Pillow is the "friendly PIL fork" by Alex Clark and Contributors. PIL is the Python Imaging Library by Fredrik Lundh and Contributors.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(lcms2)
    - pkgconfig(libopenjp2)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libwebp)
    - pkgconfig(python3)
    - pkgconfig(tk)
    - python-pytest
rundeps    :
    - libjpeg-turbo
build      : |
    %python3_setup
install    : |
    %python3_install
    install -dm00755 $installdir/usr/include/python%python3_version%/
    install -m00644 src/libImaging/*.h $installdir/usr/include/python%python3_version%/
check      : |
    %python3_test selftest.py
