name       : python-pillow
version    : 6.2.2
release    : 24
source     :
    - https://github.com/python-pillow/Pillow/archive/6.2.2.tar.gz : cc4ec754ddcc98b7166a1afe062c6355c841776145f0f23bdd3bea1eaa41e2db
license    : MIT
component  : programming.python
summary    : The friendly PIL fork (Python Imaging Library)
description: |
    Pillow is the "friendly PIL fork" by Alex Clark and Contributors. PIL is the Python Imaging Library by Fredrik Lundh and Contributors.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(lcms2)
    - pkgconfig(libopenjp2)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libwebp)
    - pkgconfig(python3)
    - pkgconfig(tk)
    - python-pytest
    - python-setuptools
rundeps    :
    - libjpeg-turbo
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
    for py in 2.7 3.7m; do
        install -dm00755 $installdir/usr/include/python${py}/
        install -m00644 src/libImaging/*.h $installdir/usr/include/python${py}/
    done
check      : |
    %python_test selftest.py
    %python3_test selftest.py
