name       : python-pillow
version    : 2.8.2
release    : 2
source     :
    - https://github.com/python-pillow/Pillow/archive/2.8.2.tar.gz : 8fde3a9da80e37db3a880c9f5ceb02cd3678d0b08da6fc33a169a1951c883b85
license    : EULA
summary    : Pillow is the "friendly PIL fork" by Alex Clark and Contributors. PIL is the Python Imaging Library by Fredrik Lundh and Contributors.
builddeps  :
     - python-setuptools
description: |
    Pillow is the "friendly PIL fork" by Alex Clark and Contributors. PIL is the Python Imaging Library by Fredrik Lundh and Contributors.
build      : |
    python setup.py build
install    : |
    python setup.py install --root=%installroot% --no-compile -O0
