name       : python-pillow
version    : 9.3.0
release    : 32
source     :
    - https://github.com/python-pillow/Pillow/archive/refs/tags/9.3.0.tar.gz : 188b2a5fd445b2afa05bc0c1318ce49d4335ebbb69417fbb79acaf0a0784709e
license    : MIT
component  : programming.python
summary    : The friendly PIL fork (Python Imaging Library)
description: |
    Pillow is the "friendly PIL fork" by Alex Clark and Contributors. PIL is the Python Imaging Library by Fredrik Lundh and Contributors.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(lcms2)
    - pkgconfig(libopenjp2)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libwebp)
    - pkgconfig(python3)
    - pkgconfig(tk)
    - python-pytest
rundeps    :
    - libjpeg-turbo
build      : |
    %python3_setup
install    : |
    %python3_install
    install -dm00755 $installdir/usr/include/python%python3_version%/
    install -m00644 src/libImaging/*.h $installdir/usr/include/python%python3_version%/
check      : |
    %python3_test selftest.py
