name       : python-pillow
version    : 3.3.0
release    : 4
source     :
    - https://github.com/python-pillow/Pillow/archive/3.3.0.tar.gz : ae2fbb500c81100f7e374545d008019e6f90918386f620625c3b3b98faf88414
license    : MIT
summary    : The friendly PIL fork (Python Imaging Library)
description: |
    Pillow is the "friendly PIL fork" by Alex Clark and Contributors. PIL is the Python Imaging Library by Fredrik Lundh and Contributors.
builddeps  :
    - python-setuptools
    - pkgconfig(python-2.7)
    - pkgconfig(python-3.5)
    - libjpeg-turbo-devel
    - pkgconfig(libtiff-4)
    - pkgconfig(freetype2)
    - pkgconfig(lcms2)
    - pkgconfig(libwebp)
    - pkgconfig(tcl)
rundeps :
    - libjpeg-turbo
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
