name       : python-pillow
version    : 4.0.0
release    : 9
source     :
    - https://github.com/python-pillow/Pillow/archive/4.0.0a.tar.gz : d498837f6c84d0fad9ef414dc0e9ee0b8d45d10efebc72898ed15950f111ad55
license    : MIT
component  : programming.python
summary    : The friendly PIL fork (Python Imaging Library)
description: |
    Pillow is the "friendly PIL fork" by Alex Clark and Contributors. PIL is the Python Imaging Library by Fredrik Lundh and Contributors.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(lcms2)
    - pkgconfig(libtiff-4)
    - pkgconfig(libwebp)
    - pkgconfig(python3)
    - pkgconfig(tcl)
    - python-setuptools
    - libjpeg-turbo-devel
rundeps    :
    - libjpeg-turbo
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
    for py in 2 3; do
        includedir=$(python$py -c 'import distutils.sysconfig; print(distutils.sysconfig.get_python_inc())')
        install -dm644 $installdir/$includedir
        install -Dm644 libImaging/*.h $installdir/$includedir
    done
