name       : python-pillow
version    : 3.4.2
release    : 7
source     :
    - https://github.com/python-pillow/Pillow/archive/3.4.2.tar.gz : 0ee762ab924e004b7e69643b44e82cf65e0fa1f16862e11bd821950dbbc5f3d3
license    : MIT
component  : programming.python
summary    : The friendly PIL fork (Python Imaging Library)
description: |
    Pillow is the "friendly PIL fork" by Alex Clark and Contributors. PIL is the Python Imaging Library by Fredrik Lundh and Contributors.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(lcms2)
    - pkgconfig(libtiff-4)
    - pkgconfig(libwebp)
    - pkgconfig(python-2.7)
    - pkgconfig(python-3.5)
    - pkgconfig(tcl)
    - python-setuptools
    - libjpeg-turbo-devel
rundeps    :
    - libjpeg-turbo
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
