name       : python-pillow
version    : 2.8.2
release    : 3
source     :
    - https://github.com/python-pillow/Pillow/archive/2.8.2.tar.gz : 8fde3a9da80e37db3a880c9f5ceb02cd3678d0b08da6fc33a169a1951c883b85
license    : EULA
summary    : Pillow is the "friendly PIL fork" by Alex Clark and Contributors. PIL is the Python Imaging Library by Fredrik Lundh and Contributors.
description: |
    Pillow is the "friendly PIL fork" by Alex Clark and Contributors. PIL is the Python Imaging Library by Fredrik Lundh and Contributors.
builddeps  :
    - python-setuptools
    - pkgconfig(python-2.7)
    - pkgconfig(python-3.5)
build      : |
    for py in "python" "python3" ; do
        ${py} setup.py build
    done
install    : |
    for py in "python" "python3" ; do
        ${py} setup.py install --root=%installroot% --no-compile -O0
    done
